FROM node:18-alpine

# Installer les dépendances système
RUN apk add --no-cache libc6-compat curl

# Créer le répertoire de travail
WORKDIR /app

# Copier le code source
COPY . .

# Installer les dépendances
RUN npm install

# Variable d'environnement pour le build
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NODE_ENV=production

# Build l'application Next.js
RUN npm run build

# Exposer le port
EXPOSE 5500

# Commande de démarrage
CMD ["npm", "start"]
