services:
  postgres:
    image: postgres:15-alpine
    container_name: tappplus-postgres
    environment:
      POSTGRES_DB: meditache
      POSTGRES_USER: meditache
      POSTGRES_PASSWORD: meditache123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meditache"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tappplus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: tappplus-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://meditache:meditache123@postgres:5432/meditache
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      TZ: Africa/Douala
      API_PORT: 5550
    ports:
      - "5550:5550"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api/src:/app/src
      - ./apps/api/prisma:/app/prisma
      - /app/node_modules
      - /app/dist

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: tappplus-web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5550
    ports:
      - "5500:5500"
    depends_on:
      - api
    volumes:
      - ./apps/web/src:/app/src
      - ./apps/web/public:/app/public
      - /app/node_modules
      - /app/.next

  worker:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: tappplus-worker
    command: ["node", "dist/worker.js"]
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://meditache:meditache123@postgres:5432/meditache
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      TZ: Africa/Douala
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api/src:/app/src
      - ./apps/api/prisma:/app/prisma
      - /app/node_modules
      - /app/dist

volumes:
  postgres_data:
  redis_data:
